export const PUT_N_HEROES = 'PUT_N_HEROES'
export const DELETE_HERO = 'DELETE_HERO'
export const ADD_HERO = 'ADD_HERO'

export const SHOW_ADD_HERO_DIALOG = 'SHOW_ADD_HERO_DIALOG'
export const SHOW_DELETE_HERO_DIALOG = 'SHOW_DELETE_HERO_DIALOG'
export const HIDE_DIALOG = 'HIDE_DIALOG'